### ISSUE TITLE
Electronic Standards

### ISSUE THREAD

**Issue by aagarden** [vtattyba/University-at-Buffalo-Micro-g-NExT-Team-#8]
Is there some sort of standard electronics should be upholding?

**Comment by teresabompczyk** [comment]
Linking [Drive doc ](https://docs.google.com/document/d/1_I_kJzhW4q7bZrrGD3oqbZk82YqjiK_houwkaA-p9fY/edit?usp=sharing)Allison created, thank you!

**Comment by aagarden** [comment]
Let me know if you guys think any of this is useful. If not I can try looking for other stuff or anything else needed.
